name: ğŸ„ Advent of Code Badges ğŸ„
on:
  schedule:
    - cron: '3 12 1-13 12 *'
  workflow_dispatch:
  push:
    paths:
      - '**/Day*.kt' # only if a days source file was modified
jobs:
  build:
    name: â­ Update badges ğŸ“…
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'derNiklaas') # don't run in forks
    steps:
      - uses: actions/checkout@v4
      - uses: J0B10/aoc-badges-action@v3
        with:
          userid: 455680
          session: ${{ secrets.AOC_SESSION }}
          year: 2025
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update badges
          file_pattern: README.md